# 多参差模糊综合评价

代码为单层次，需要的时候自己调

# Step 1. 确定隶属度
根据数据分布特性构造隶属函数，此处只使用梯形型的偏大偏小以及中间型


## 函数构造

- 偏小型：

In [8]:
import numpy as np
def trapezoid_min(x, a, d):
    """
    梯形隶属函数。
    
    :param x: 输入值
    :param a: 左端点
    :param b: 中间左点
    :param c: 中间右点
    :param d: 右端点
    :return: 隶属度
    """
    if x <= a:
        return 1
    elif a <= x <= d:
        return (d-x)/(d-a)
    else:  # x > d
        return 0


- 中间型：

In [ ]:
def trapezoid_mid(x, a, b, c, d):
    """
    梯形隶属函数。
    
    :param x: 输入值
    :param a: 左端点
    :param b: 中间左点
    :param c: 中间右点
    :param d: 右端点
    :return: 隶属度
    """
    if x <= a:
        return 0
    elif a <= x <= b:
        return (x - a) / (b - a)
    elif b < x <= c:
        return 1
    elif c < x <= d:
        return (d - x) / (d - c)
    else:  # x > d
        return 0

- 偏大型：

In [ ]:
def trapezoid_max(x, a, d):
    """
    梯形隶属函数。
    
    :param x: 输入值
    :param a: 左端点
    :param b: 中间左点
    :param c: 中间右点
    :param d: 右端点
    :return: 隶属度
    """
    if x <= a:
        return 0
    elif a <= x <= d:
        return (x-a)/(d-a)
    else:  # x > d
        return 1

## 构造出指标的隶属度矩阵
- X 为评价层次
- Y 为不同的指标

In [9]:
# 对每个指标选取合适的函数进行计算
membership_matrix = np.array([
     [0.18, 0.14, 0.18, 0.14, 0.13, 0.23],
     [0.15, 0.20, 0.15, 0.25, 0.10, 0.15],
     [0.25, 0.12, 0.13, 0.12, 0.18, 0.20],
     [0.16, 0.15, 0.21, 0.11, 0.20, 0.17],
     [0.23, 0.18, 0.17, 0.16, 0.15, 0.11],
     [0.19, 0.13, 0.12, 0.12, 0.11, 0.33],
     [0.17, 0.16, 0.15, 0.08, 0.25, 0.19]])

## 权重确定

- 熵权法确定所有指标相对于最终结果的权重
- 在多层次中，是低层次对高层次的权重

In [15]:
import 熵权法Exp as sq
# 输入指标的隶属度矩阵
X = np.array([
     [0.18, 0.14, 0.18, 0.14, 0.13, 0.23],
     [0.15, 0.20, 0.15, 0.25, 0.10, 0.15],
     [0.25, 0.12, 0.13, 0.12, 0.18, 0.20],
     [0.16, 0.15, 0.21, 0.11, 0.20, 0.17],
     [0.23, 0.18, 0.17, 0.16, 0.15, 0.11],
     [0.19, 0.13, 0.12, 0.12, 0.11, 0.33],
     [0.17, 0.16, 0.15, 0.08, 0.25, 0.19]])
# 隶属度矩阵转置后使用熵权法，得到每一个评价指标的权重
X = X.T
# 获得权重矩阵
weights = sq.entropy_weight(X)

===============熵权法启动！=======================
标准化矩阵 Z = 
[[0.43176518 0.35355339 0.58827601 0.38445547 0.55075011 0.42190981
  0.39848615]
 [0.33581737 0.47140452 0.28237248 0.360427   0.43102183 0.28867513
  0.37504578]
 [0.43176518 0.35355339 0.30590352 0.5045978  0.40707617 0.26646936
  0.35160542]
 [0.33581737 0.58925565 0.28237248 0.26431313 0.38313051 0.26646936
  0.18752289]
 [0.31183041 0.23570226 0.42355872 0.48056933 0.35918486 0.24426358
  0.58600904]
 [0.55169996 0.35355339 0.47062081 0.40848393 0.26340223 0.73279073
  0.44536687]]
权重 W = 
[0.07221732 0.1374572  0.14167441 0.07101407 0.08126827 0.32662567
 0.16974307]
===============熵权法结束=======================


- AHP确定权重

In [14]:
import AHPFunc as AHP
# 输入判断矩阵,必须是方阵，不用转置
X = np.array([
     [0.18, 0.14, 0.18, 0.14, 0.13, 0.23],
     [0.15, 0.20, 0.15, 0.25, 0.10, 0.15],
     [0.25, 0.12, 0.13, 0.12, 0.18, 0.20],
     [0.16, 0.15, 0.21, 0.11, 0.20, 0.17],
     [0.23, 0.18, 0.17, 0.16, 0.15, 0.11],
     [0.19, 0.13, 0.12, 0.12, 0.11, 0.33]])
# 获得权重矩阵
weights = AHP.AHP(X)

===============AHP启动！=======================
CI= (-1+0j)
RI= (-0.7352941176470588+0j)
CR<0.10, correct! 
ASum= [1.16 0.92 0.96 0.9  0.87 1.19]
[[0.155 0.152 0.188 0.156 0.149 0.193]
 [0.129 0.217 0.156 0.278 0.115 0.126]
 [0.216 0.13  0.135 0.133 0.207 0.168]
 [0.138 0.163 0.219 0.122 0.23  0.143]
 [0.198 0.196 0.177 0.178 0.172 0.092]
 [0.164 0.141 0.125 0.133 0.126 0.277]]
[0.167 0.167 0.167 0.167 0.167 0.167]
weighs are:  [0.165831, 0.17050700000000002, 0.16516300000000003, 0.16950500000000002, 0.169171, 0.16132200000000002]
===============AHP结束=======================


# Step2. 合成权重，得到评价

## 权重合成

In [16]:
print(weights)
print(membership_matrix)

[0.07221732 0.1374572  0.14167441 0.07101407 0.08126827 0.32662567
 0.16974307]
[[0.18 0.14 0.18 0.14 0.13 0.23]
 [0.15 0.2  0.15 0.25 0.1  0.15]
 [0.25 0.12 0.13 0.12 0.18 0.2 ]
 [0.16 0.15 0.21 0.11 0.2  0.17]
 [0.23 0.18 0.17 0.16 0.15 0.11]
 [0.19 0.13 0.12 0.12 0.11 0.33]
 [0.17 0.16 0.15 0.08 0.25 0.19]]


In [17]:
weights = np.array(weights)

marks = np.dot(weights,membership_matrix)
print("评分为：")
print(marks)

评分为：
[0.19000545 0.14950342 0.14542047 0.13506465 0.15339301 0.226613  ]
